### PR TITLE
Fix filtering 

### LINKED ISSUE #8: accounts form bug
Hi - not sure if this is a work in progress or if i'm using it incorrectly but for the accounts tab in the relay extension, when i add a npub it doesn't seem to register the data in the table below. 

I am using direct from main branch, and pull from main branch yesterday, April 5, 2023

Screenshot 2023-04-06 at 1 54 21 PM

### PR DESCRIPTION
**Pull request by talvasconcelos**
Instead of asking the DB for the accounts, we now call it once and filter client side! Filtering now works as expected.

@motorina0 , when toggling, in the account row, shouldn't the toggles be allowed OR blocked? and never the two at the same time? or is it that a user can be blocked for some time, if the OP whiches? If the later, PR is ready, if not I'll fix it also.

Closes #8

### CODE REVIEW

**Comment by motorina0** [comment]
A relay can in theory have 100k+ accounts, out of which only a few hundreds are blocked or explicitly allowed.

@talvasconcelos Would the approach in this PR fetch all 100k+ all the time?

**Comment by talvasconcelos** [comment]
yes, and I see your point. i need to rethink this.

the get wasn't retrieving anything from the DB, though.

**Comment by talvasconcelos** [comment]
@motorina0 filtering is working on testing. Can you please make a final review ?

File: static/components/relay-details/relay-details.js [hunk 1]
```diff
@@ -224,6 +238,7 @@ async function relayDetails(path) {
               blocked: ops.blocked
             }
           )
+          console.log(ops)
```
Comment (motorina0) [inline static/components/relay-details/relay-details.js:241]: - extra log statement

File: views_api.py [hunk 2]
```diff
@@ -208,7 +209,7 @@ async def api_create_or_update_account(
             account.blocked = data.blocked
         if data.allowed is not None:
             account.allowed = data.allowed
-
+        print(data, account)
```
Comment (motorina0) [inline views_api.py:212]: extra log statement

File: static/components/relay-details/relay-details.js [hunk 3]
```diff
@@ -105,6 +104,9 @@ async function relayDetails(path) {
         return (
           'wss://' + this.relay.config.domain + '/nostrrelay/' + this.relay.id
         )
+      },
+      accountsFilter(){
```
Comment (motorina0) [inline static/components/relay-details/relay-details.js:108]: where is this method used?

File: static/components/relay-details/relay-details.js [hunk 4]
```diff
@@ -184,6 +186,18 @@ async function relayDetails(path) {
           LNbits.utils.notifyApiError(error)
         }
       },
+      accountsFilterMethod(rows){
```
Comment (motorina0) [inline static/components/relay-details/relay-details.js:189]: is client side filtering still needed?

**Comment by bitkarrot** [comment]
Thank you! @talvasconcelos @motorina0
